### ISSUE TITLE
The application must be able to detect if a box is opened in an image, whenever the inside is recognizable

### ISSUE THREAD

**Issue by Jasperkroes** [egedebruin/Trackscape#4]
When an image of a box is given 
and the inside of this box is visible 
then the application will say that the box is open

When an image of a box is given
and the inside of the box is not visible
then the application should say that the box is closed

DoD:
This issue is done when the system can 100% of the time give a good prediction when a box is opened and 80%+ when the box is closed.
The code should be tested with **100% branch coverage**

**Comment by lisv** [comment]
Will be optimized next sprint.
