### ISSUE TITLE
Display progress of the game in Gui

### ISSUE THREAD

**Issue by lisv** [egedebruin/Trackscape#40]
* Show how far along the game is, with e.g. text or a bar that can be filled up
* Progress is for now based on amount of open chests

**Comment by Jasperkroes** [comment]
Ik denk dat we hiervoor het best iets van een progressie object oid kunnen maken, dat bijhoud hoeveel kisten er open zijn ed, en die dan laten zien in de GUI. Die balk is wel mooi maar dat zegt vrij weinig over tijd, misschien handig als we daar ook al gelijk rekening mee houden.

We moeten bij zo'n progressie balk misschien ook al iets maken dat aangeeft dat de spelers achterlopen, dit kunnen we misschien doen door een uitroepteken te laten zien of de progressiebalk rood te maken.
