### ISSUE TITLE
Think and decide about things to show in the log

### ISSUE THREAD

**Issue by lisv** [egedebruin/Trackscape#42]
* When game is started (activity begins)
* When chest is found
* When there is suddenly lots of activity? ("People are rushing!")
* What else could be useful?

**Comment by Jasperkroes** [comment]
ik denk dat punt 3, over de activiteit, het beste ergens anders kan staan dan in de log. 
Het beste is denk ik dat we in de log alleen dingen showen die ook daadwerkelijk handig zijn om te weten om de progress te kunnen bepalen, zoals wanneer een kist is geopend.
