### ISSUE TITLE
Process SIG feedback in code

### ISSUE THREAD

**Issue by lisv** [egedebruin/Trackscape#56]

**Comment by Jasperkroes** [comment]
Beste,

Hierbij ontvang je onze evaluatie van de door jou opgestuurde code. De evaluatie bevat een aantal aanbevelingen die meegenomen kunnen worden in de laatste fase van het project.

Deze evaluatie heeft als doel om studenten bewuster te maken van de onderhoudbaarheid van hun code en dient niet gebruikt te worden voor andere doeleinden.

Mochten er nog vragen of opmerkingen zijn dan hoor ik dat graag.

Met vriendelijke groet,
Dennis Bijlsma



[Feedback]

De code van het systeem scoort 4.0 sterren op ons onderhoudbaarheidsmodel, wat betekent dat de code marktgemiddeld onderhoudbaar is. We zien Module Coupling en Unit Size vanwege de lagere deelscores als mogelijke verbeterpunten.

Voor Module Coupling wordt er gekeken naar het percentage van de code wat relatief vaak wordt aangeroepen. Normaal gesproken zorgt code die vaak aangeroepen wordt voor een minder stabiel systeem omdat veranderingen binnen dit type code kan leiden tot aanpassingen op veel verschillende plaatsen. Dit soort code wordt niet alleen vaak aangeroepen, maar wordt vaak ook vanzelf groter omdat alle functionaliteit owordt gecentraliseerd. Om zowel de grootte als het aantal aanroepen te verminderen zouden deze functionaliteiten gescheiden kunnen worden, wat er ook toe zou leiden dat de afzonderlijke functionaliteiten makkelijker te begrijpen, te testen en daardoor eenvoudiger te onderhouden worden.

In jullie project wordt MainController het vaakst aangeroepen. De naam van die class geeft eigenlijk al aan dat er geen duidelijke verantwoordelijkheid is. Iedereen gebruikt nu MainController, en MainController geeft op zijn beurt weer toegang tot alle andere controllers. Zo'n "iedereen praat met iedereen" architectuur leidt op termijn tot een enorme hoeveelheid afhankelijkheden, wat er voor gaat zorgen dat een aanpassing in class A altijd ook tot een aanpassing in class B, C, en D leidt. Probeer daarom eerst te definiëren welke classes met elkaar zouden mogen praten.

Voor Unit Size wordt er gekeken naar het percentage code dat bovengemiddeld lang is. Het opsplitsen van dit soort methodes in kleinere stukken zorgt ervoor dat elk onderdeel makkelijker te begrijpen, te testen en daardoor eenvoudiger te onderhouden wordt. Binnen de langere methodes in dit systeem, zoals bijvoorbeeld, zijn aparte stukken functionaliteit te vinden welke ge-refactored kunnen worden naar aparte methodes.

In jullie project is MediaBar.createMediaBar() een goed voorbeeld. Jullie hebben dat nu als één grote methode uitgeschreven, terwijl je aan het commentaar kunt zien dat er eigenlijk verschillende stappen in het proces zijn. Door die stappen met codestructuur aan te geven, bijvoorbeeld door nieuwe methodes te maken per stap, zorg je er voor dat je de code op lange termijn begrijpelijk houdt.

De aanwezigheid van testcode is in ieder geval veelbelovend. De hoeveelheid tests blijft nog wel wat achter bij de hoeveelheid productiecode, hopelijk lukt het nog om dat tijdens het vervolg van het project te laten stijgen.

Over het algemeen is er dus nog wat verbetering mogelijk, hopelijk lukt het om dit tijdens de rest van de ontwikkelfase te realiseren.

**Comment by lisv** [comment]
#67

**Comment by lisv** [comment]
All that is left to do for SIG is add more tests (for the Gui parts)
