### ISSUE TITLE
The application must be able to detect whether a person is moving or not in a short video.

### ISSUE THREAD

**Issue by Jasperkroes** [egedebruin/Trackscape#6]
When given a video of a person still standing
Then the application should recognize that the person is standing

When given a video of a moving person
then the application should recognize that the person is moving

DoD:
This issue is done whenever the application can differentiate between walking and still standing correctly
The code should be tested with **100% branch coverage**

**Comment by lisv** [comment]
Activity is detected, but not per each person. We decided that this may not be important after all though, so next sprint we will work on how we can use activity to map where persons are and if they are moving around a lot or not.
